server:
  port: ${PORT:8020}

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: load-from-config-server
    password: load-from-config-server
  jpa:
    hibernate:
      ddl-auto: update

axon:
  eventhandling:
    processors:
      order:
        mode: subscribing
  deadlinemanager:
    enable: true