server:
  port: ${PORT:8010}

spring:
  application:
    name: product-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  datasource:
    url: jdbc:mysql://localhost:3306/product-service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: load-from-config-server
    password: load-from-config-server
  jpa:
    hibernate:
      ddl-auto: update

axon:
  eventhandling:
    processors:
      product:
        mode: tracking # set to tracking to replay events
#        mode: subscribing

logging:
  level:
    org.axonframework.axonserver.connector.event.axon.AxonServerEventStore: DEBUG